apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-service
  template:
    metadata:
      labels:
        app: add-service
    spec:
      containers:
      - name: add-container
        image: localhost/add-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  type: NodePort
  selector:
    app: add-service
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007