apiVersion: apps/v1
kind: Deployment
metadata:
  name: div-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: div-service
  template:
    metadata:
      labels:
        app: div-service
    spec:
      containers:
        - name: div-service
          image: div-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: div-service
spec:
  type: NodePort
  selector:
    app: div-service
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30020